### ISSUE TITLE
Sugestão vinda de um penetra

### ISSUE THREAD

**Issue by vmesel** [dunossauro/linguistica-de-corpus#7]
Edão, sei q este projeto é para sua faculdade e etc, mas aqui vai uma sugestão, que tal você poder fazer com que a página tenha um textbox para o processamento de texto, ao invés da pessoa ter de salvar o txt.

Acredito que os usuários semi-linguistas ficariam felizes!

**Comment by vmesel** [comment]
Ah, detalhe, eu tentei dar deploy no heroku para eu testar, mas não rolou, dps se vc tiver interesse eu te conto como eu tentei contornar esses problemas para a gente achar uma solução

**Comment by dunossauro** [comment]
Cara, ele gera o arquivo, pois se for grande vai ser jogado no spark e
enviado por e-mail.

Os programas de linguística no geral funcionam inserindo os arquivos

Em 17 de maio de 2016 12:44, Vinicius Mesel notifications@github.com
escreveu:

> Ah, detalhe, eu tentei dar deploy no heroku para eu testar, mas não rolou,
> dps se vc tiver interesse eu te conto como eu tentei contornar esses
> problemas para a gente achar uma solução
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/z4r4tu5tr4/linguistica-de-corpus/issues/7#issuecomment-219760284

## 

Eduardo []

**Comment by vmesel** [comment]
Entendi, beleza, não tinha pensado nessa possibilidade.
Interessante a parte do spark, vou dar uma olhada nisso! valeu Edão!
